apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: <% .Name %>
  env: secrets.env

# Don't add a suffix to the secret name
generatorOptions:
  disableNameSuffixHash: true
