# This will pull the contents of a secret from AWS Secret Manager and put it into a Kubernetes secret.
# Any changes made to the AWS secret should be automatically synced over.
# An AWS secret for the project should have been created automatically by /scripts/create-db-user.sh in the infrastructure project
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: <% .Name %>
spec:
  backendType: secretsManager
  dataFrom:
  - <% .Name %>/kubernetes/stage/<% .Name %>
