apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml
- cronjob.yml
<%if eq (index .Params `userAuth`) "yes" %>- auth.yml
<% end %>
configMapGenerator:
- name: <% .Name %>-config
  literals:
    - DATABASE_ENGINE=<% index .Params `database` %>
    - DATABASE_HOST=database.<% .Name %>
    - DATABASE_PORT=<%if eq (index .Params `database`) "postgres" %>5432<% else if eq (index .Params `database`) "mysql" %>3306<% end %>
    - DATABASE_NAME=<% index .Params `databaseName` %>
    - CACHE_ENGINE=<% index .Params `cacheStore` %>
    - CACHE_ENDPOINT=cache-<% index .Params `cacheStore` %>.<% .Name %>
    - CACHE_PORT=<%if eq (index .Params `cacheStore`) "redis" %>6379<% else if eq (index .Params `cacheStore`) "memcached" %>11211<% end %>
    - SERVICE_PORT=80

commonLabels:
  app: <% .Name %>
