apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

configMapGenerator:
- name: <% .Name %>-config
  literals:
    - DATABASE_ENGINE=<% index .Params `database` %>
    - DATABASE_HOST=database.<% .Name %>
    - DATABASE_PORT=<%if eq (index .Params `database`) "postgres" %>5432<% else if eq (index .Params `database`) "mysql" %>3306<% end %>
    - DATABASE_NAME=<% index .Params `databaseName` %>
    - SERVICE_PORT=80

commonLabels:
  app: <% .Name %>
